import './globals.css'
import { Inter } from 'next/font/google'
import styles from './page.module.css'
import Header from '@/components/shared/header'
import Footer from '@/components/shared/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.className}>
        <Header />
        {children}
        <Footer className={styles.footer}/>
      </body>
    </html>
  )
}
